name: Update the space state manually

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sed -e "s/\${open}/true/" -e "s/\${lastchange}/$(date +%s)/" template.json > spaceapi.json
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
