name: Update the space state

on:
  repository_dispatch:
    types: do-something
jobs:
  build:
    name: Run Some Thing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo hello > world.txt

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: world.txt
